# Generated by Django 6.0.1 on 2026-01-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_column='product_id', unique=True)),
                ('productDisplayName', models.TextField(db_column='product_display_name')),
                ('masterCategory', models.CharField(db_column='master_category', max_length=100)),
                ('subCategory', models.CharField(db_column='sub_category', max_length=100)),
                ('articleType', models.CharField(db_column='article_type', max_length=100)),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('link', models.URLField(db_column='link', max_length=500)),
                ('gender', models.CharField(db_column='gender', max_length=50)),
                ('season', models.CharField(db_column='season', max_length=50)),
                ('year', models.IntegerField(db_column='year')),
                ('usage', models.CharField(db_column='usage', max_length=100)),
                ('color', models.CharField(db_column='color', max_length=50)),
                ('price', models.FloatField(db_column='price')),
                ('brand', models.CharField(db_column='brand', max_length=100)),
                ('silhouette', models.CharField(blank=True, db_column='silhouette', max_length=100, null=True)),
                ('figure', models.CharField(blank=True, db_column='figure', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
