# Generated by Django 6.0.1 on 2026-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('gender', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('usage', models.CharField(max_length=100)),
                ('master_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('article_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('silhouette', models.CharField(blank=True, max_length=100, null=True)),
                ('figure', models.CharField(blank=True, max_length=100, null=True)),
                ('product_display_name', models.CharField(max_length=255)),
            ],
        ),
    ]
