# Generated by Django 6.0.1 on 2026-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
